const { existsSync, mkdtempSync, rmSync, writeFileSync } = require("fs");
const { tmpdir } = require("os");
const { spawnSync } = require("child_process");
const path = require("path");

const defaultRoot = path.resolve(__dirname, "..");
const migrations = [
  "docs/marketing_os_v5_6_5_phase_0_1_schema.sql",
  "docs/marketing_os_v5_6_5_phase_0_1_schema_patch_001.sql",
  "docs/marketing_os_v5_6_5_phase_0_1_schema_patch_002.sql"
];
const migrationLockKey = [565006, 565001];

function validateMigrationFiles(root = defaultRoot) {
  return migrations.filter((file) => !existsSync(path.join(root, file)));
}

function isStrictMode(options = {}) {
  return Boolean(options.strict || process.argv.includes("--strict") || process.env.CI === "true" || process.env.STRICT_GATES === "true");
}

function escapePsqlIncludePath(filePath) {
  return filePath.replace(/\\/g, "/").replace(/'/g, "''");
}

function buildMigrationDriver(root = defaultRoot) {
  const lines = [
    "-- Generated by scripts/db-migrate.js",
    "-- Serializes migration execution for concurrent integration-test processes.",
    `SELECT pg_advisory_lock(${migrationLockKey[0]}, ${migrationLockKey[1]});`,
    ""
  ];

  for (const migration of migrations) {
    const migrationPath = path.join(root, migration);
    lines.push(`\\echo Applying ${migration}`);
    lines.push(`\\i '${escapePsqlIncludePath(migrationPath)}'`);
    lines.push("");
  }

  lines.push(`SELECT pg_advisory_unlock(${migrationLockKey[0]}, ${migrationLockKey[1]});`);
  lines.push("");

  return lines.join("\n");
}

const SERVICE_NAME = "marketing_os_migration";
const FORBIDDEN_SERVICE_CHARS = /[\r\n\x00]/;
const SUPPORTED_PARAMS = ["sslmode", "application_name", "connect_timeout"];

function parseDatabaseUrl(databaseUrl) {
  let url;
  try {
    url = new URL(databaseUrl);
  } catch {
    return null;
  }
  if (url.protocol !== "postgres:" && url.protocol !== "postgresql:") {
    return null;
  }

  const safe = (val) => (FORBIDDEN_SERVICE_CHARS.test(val) ? null : val);

  const fields = {};

  if (url.hostname) {
    const host = safe(decodeURIComponent(url.hostname));
    if (host === null) return null;
    fields.host = host;
  }

  if (url.port) {
    const port = safe(url.port);
    if (port === null) return null;
    fields.port = port;
  }

  const dbname = decodeURIComponent(url.pathname.slice(1));
  if (dbname) {
    const safeName = safe(dbname);
    if (safeName === null) return null;
    fields.dbname = safeName;
  }

  if (url.username) {
    const user = safe(decodeURIComponent(url.username));
    if (user === null) return null;
    fields.user = user;
  }

  if (url.password) {
    const password = safe(decodeURIComponent(url.password));
    if (password === null) return null;
    fields.password = password;
  }

  for (const param of SUPPORTED_PARAMS) {
    const val = url.searchParams.get(param);
    if (val !== null) {
      const safeVal = safe(val);
      if (safeVal === null) return null;
      fields[param] = safeVal;
    }
  }

  return fields;
}

function runMigrationsWithLock({ root, env, spawnSyncRunner = spawnSync }) {
  const databaseUrl = env.DATABASE_URL;
  if (!databaseUrl) {
    console.error("DATABASE_URL is required.");
    return 1;
  }

  const parsed = parseDatabaseUrl(databaseUrl);
  if (!parsed) {
    console.error("DATABASE_URL must be a valid postgres:// or postgresql:// URL.");
    return 1;
  }

  const tempDir = mkdtempSync(path.join(tmpdir(), "marketing-os-migrations-"));
  const driverPath = path.join(tempDir, "migration-driver.sql");
  const serviceFilePath = path.join(tempDir, "pgservice.conf");

  try {
    writeFileSync(driverPath, buildMigrationDriver(root), "utf8");

    const serviceLines = [`[${SERVICE_NAME}]`];
    for (const [key, value] of Object.entries(parsed)) {
      serviceLines.push(`${key}=${value}`);
    }
    serviceLines.push("");
    writeFileSync(serviceFilePath, serviceLines.join("\n"), { encoding: "utf8", mode: 0o600 });

    const childEnv = { ...process.env, ...env };
    delete childEnv.DATABASE_URL;
    delete childEnv.DATABASE_URI;
    childEnv.PGSERVICEFILE = serviceFilePath;
    childEnv.PGSERVICE = SERVICE_NAME;

    const result = spawnSyncRunner("psql", ["service=marketing_os_migration", "-v", "ON_ERROR_STOP=1", "-f", driverPath], {
      stdio: "inherit",
      env: childEnv
    });

    return result.status ?? 1;
  } finally {
    rmSync(tempDir, { recursive: true, force: true });
  }
}

function run(options = {}) {
  const strict = isStrictMode(options);
  const root = options.root || defaultRoot;
  const env = options.env || process.env;
  const missing = validateMigrationFiles(root);

  if (missing.length > 0) {
    const message = `Migration files not present in this checkout: ${missing.join(", ")}`;
    if (strict) {
      console.error(message);
      console.error("Strict Sprint 0 migration gate requires the approved SQL files to be present.");
      return 1;
    }
    console.warn(message);
    console.warn("Local migration gate validated wiring only; full repository checkouts include these approved SQL files.");
    return 0;
  }

  if (!env.DATABASE_URL) {
    if (strict) {
      console.error("DATABASE_URL is required for strict Sprint 0 migration execution.");
      return 1;
    }
    console.log(`Validated migration order:\n${migrations.map((file, index) => `${index + 1}. ${file}`).join("\n")}`);
    console.log("Set DATABASE_URL to apply migrations with psql.");
    return 0;
  }

  const psqlCheck = spawnSync("psql", ["--version"], { stdio: "ignore" });
  if (psqlCheck.error) {
    console.error("psql is required for Sprint 0 migration execution.");
    return 1;
  }

  return runMigrationsWithLock({ root, env });
}

if (require.main === module) {
  process.exit(run());
}

module.exports = {
  buildMigrationDriver,
  escapePsqlIncludePath,
  isStrictMode,
  migrations,
  migrationLockKey,
  parseDatabaseUrl,
  run,
  runMigrationsWithLock,
  validateMigrationFiles
};
