const roles = [
  ["owner", "Owner"],
  ["admin", "Admin"],
  ["creator", "Creator"],
  ["reviewer", "Reviewer"],
  ["publisher", "Publisher"],
  ["billing_admin", "BillingAdmin"],
  ["viewer", "Viewer"]
].map(([role_code, role_name]) => ({ role_code, role_name, role_scope: "workspace", is_system_role: true }));

const permissions = [
  "workspace.read",
  "workspace.create",
  "workspace.manage",
  "workspace.manage_members",
  "rbac.read",
  "billing.read",
  "brand.read",
  "brand.write",
  "prompt_template.read",
  "prompt_template.write",
  "report_template.read",
  "report_template.write",
  "campaign.read",
  "campaign.write",
  "brief.read",
  "brief.write",
  "media_job.read",
  "media_job.create",
  "media_job.update_status",
  "media_asset.read",
  "media_asset.create",
  "media_asset.version_create",
  "review.read",
  "review.assign",
  "approval.decide",
  "publish_job.create",
  "manual_evidence.read",
  "manual_evidence.submit",
  "manual_evidence.invalidate",
  "tracked_link.read",
  "tracked_link.create",
  "report.read",
  "report.generate",
  "usage.read",
  "usage.record",
  "cost.read",
  "cost.record",
  "cost_budget.read",
  "cost_budget.write",
  "cost_guardrail.read",
  "cost_guardrail.write",
  "audit.read",
  "operations.read",
  "operations.safe_mode",
  "onboarding.read",
  "onboarding.write",
  "connector.read",
  "connector.write",
  "connector.rotate_secret",
  "webhook.receive",
  "performance.read",
  "performance.event_create",
  "performance.snapshot_create",
  "contact.read",
  "contact.create",
  "contact.update",
  "contact.consent_update",
  "lead_capture.read",
  "lead_capture.create",
  "notification_rule.read",
  "notification_rule.write",
  "notification_delivery.read",
  "nashir.campaign.read",
  "nashir.campaign.write",
  "nashir.evidence.submit",
  "nashir.approval.decide",
  "nashir.store.read",
  "nashir.store.update",
  "nashir.product.read",
  "nashir.product.write",
  "nashir.asset.read",
  "nashir.asset.write",
  "nashir.asset.link",
  "nashir.content.read",
  "nashir.content.create",
  "nashir.content.update",
  "nashir.content.submit_review",
  "nashir.creator_studio.use",
  "nashir.creator_studio.transfer.create",
  "nashir.publishing.queue.read",
  "nashir.publishing.draft.receive",
  "nashir.evidence.manage",
  "nashir.prompt_governance.read",
  "nashir.prompt_governance.manage",
  "nashir.model_routing.read",
  "nashir.model_routing.manage",
  "nashir.cost.read",
  "nashir.cost.manage",
  "nashir.workflow.read",
  "nashir.admin.manage"
].map((permission_code) => ({
  permission_code,
  permission_name: permission_code,
  domain: permission_code.split(".")[0]
}));

const rolePermissions = {
  owner: permissions.map((permission) => permission.permission_code),
  admin: permissions
    .map((permission) => permission.permission_code)
    .filter((code) => !["usage.record", "cost.record", "webhook.receive"].includes(code)),
  creator: [
    "workspace.read",
    "rbac.read",
    "brand.read",
    "brand.write",
    "prompt_template.read",
    "prompt_template.write",
    "report_template.read",
    "campaign.read",
    "campaign.write",
    "brief.read",
    "brief.write",
    "media_job.read",
    "media_job.create",
    "media_asset.read",
    "media_asset.create",
    "media_asset.version_create",
    "review.read",
    "review.assign",
    "connector.read",
    "performance.read",
    "performance.event_create",
    "performance.snapshot_create",
    "contact.read",
    "contact.create",
    "contact.update",
    "contact.consent_update",
    "lead_capture.read",
    "lead_capture.create",
    "notification_rule.read",
    "notification_delivery.read",
    "nashir.campaign.read",
    "nashir.campaign.write",
    "nashir.store.read",
    "nashir.product.read",
    "nashir.product.write",
    "nashir.asset.read",
    "nashir.asset.write",
    "nashir.asset.link",
    "nashir.content.read",
    "nashir.content.create",
    "nashir.content.update",
    "nashir.content.submit_review",
    "nashir.creator_studio.use",
    "nashir.creator_studio.transfer.create",
    "nashir.publishing.queue.read",
    "nashir.prompt_governance.read"
  ],
  reviewer: [
    "workspace.read",
    "rbac.read",
    "campaign.read",
    "brief.read",
    "media_asset.read",
    "review.read",
    "approval.decide",
    "performance.read",
    "contact.read",
    "lead_capture.read",
    "notification_rule.read",
    "notification_delivery.read",
    "nashir.campaign.read",
    "nashir.approval.decide",
    "nashir.store.read",
    "nashir.product.read",
    "nashir.asset.read",
    "nashir.content.read",
    "nashir.publishing.queue.read",
    "nashir.prompt_governance.read"
  ],
  publisher: [
    "workspace.read",
    "rbac.read",
    "campaign.read",
    "media_job.read",
    "media_asset.read",
    "review.read",
    "publish_job.create",
    "manual_evidence.read",
    "manual_evidence.submit",
    "manual_evidence.invalidate",
    "tracked_link.read",
    "tracked_link.create",
    "connector.read",
    "performance.read",
    "performance.event_create",
    "contact.read",
    "contact.create",
    "lead_capture.read",
    "lead_capture.create",
    "notification_rule.read",
    "notification_delivery.read",
    "nashir.campaign.read",
    "nashir.evidence.submit",
    "nashir.store.read",
    "nashir.product.read",
    "nashir.asset.read",
    "nashir.content.read",
    "nashir.publishing.queue.read",
    "nashir.publishing.draft.receive"
  ],
  billing_admin: [
    "workspace.read",
    "rbac.read",
    "billing.read",
    "usage.read",
    "cost.read",
    "cost_budget.read",
    "cost_budget.write",
    "cost_guardrail.read",
    "cost_guardrail.write",
    "performance.read",
    "nashir.store.read",
    "nashir.cost.read",
    "nashir.cost.manage"
  ],
  viewer: [
    "workspace.read",
    "rbac.read",
    "brand.read",
    "prompt_template.read",
    "report_template.read",
    "campaign.read",
    "brief.read",
    "media_job.read",
    "media_asset.read",
    "review.read",
    "manual_evidence.read",
    "tracked_link.read",
    "report.read",
    "usage.read",
    "cost.read",
    "operations.read",
    "onboarding.read",
    "connector.read",
    "performance.read",
    "contact.read",
    "lead_capture.read",
    "notification_rule.read",
    "notification_delivery.read",
    "nashir.campaign.read",
    "nashir.store.read",
    "nashir.product.read",
    "nashir.asset.read",
    "nashir.content.read",
    "nashir.publishing.queue.read",
    "nashir.prompt_governance.read"
  ]
};

function hasPermission(roleCode, permissionCode) {
  return Boolean(rolePermissions[roleCode]?.includes(permissionCode));
}

module.exports = {
  hasPermission,
  permissions,
  rolePermissions,
  roles
};
